# Generated by Django 4.2 on 2023-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
