# Generated by Django 4.2 on 2023-04-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_productimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimport',
            old_name='csv_file',
            new_name='CSV',
        ),
    ]
