# Generated by Django 4.2 on 2023-04-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0003_rename_csv_file_productimport_csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
